### PR TITLE
HPC Training Book - v1.0.0

### LINKED ISSUE #1: Device Setup
Content for how to setup recruit's devices. Needs a page on setup for:

- [x] Windows
  - [x] ~~Install mingw-w64~~ (maybe)
  - [x] Or use Visual Studio and Visual C++
- [x] Linux
  - [x] Command line instructions (possibly multiple distros)
- [x] MacOS
  - [x] Homebrew install
  - [x] Xcode? (idk, I don't have a Mac)
  - [x] GCC or Clang install using Homebrew
- [x] WSL
  - [x] Possible setup of WSL (take from [HPP](https://github.com/MonashDeepNeuron/HPP))
  - [x] Setup of Remote dev between VSCode and WSL <-> Windows

All sections should include the installation of:

- [x] Git
- [x] A text editor (VSCode)

## Related and/or Linked

- #2

### LINKED ISSUE #2: GitHub Setup
## Original

- [x] Create GitHub account
- [x] Added to [DeepNeuron](https://github.com/MonashDeepNeuron) organization
- [x] Added to [HPC Recruits Team]() via email invitation
- [x] Linking Git to GitHub on recruits local machine 

## Additional

- [x] Download GitHub mobile app
- [x] Talk about watching repos to get updates for projects
- [ ] Challenges section
  - [ ] Talk about what challenges are 
  - [ ] General expectation
  - [ ] How to clone the [template repo](https://github.com/MonashDeepNeuron/HPC-Training-Challenges)
  - [ ] How to clone, add, push etc.

## Related and/or Linked

- #1 
- #4

### LINKED ISSUE #3: M3 Setup
- [x] Gain access to M3
- [x] Create person dev directory
- [x] Get access to MDN project
- [x] Get access to gurobi

### LINKED ISSUE #4: C Content
- [x] Hello World!
- [x] Compilation
  - [x] Headers files
  - [x] Source Files
  - [x] Compilation
  - [x] Linking
  - [x] ~~How GCC works (brief)~~
  - [x] ~~Using GCC~~
- [x] Types and Variables
  - [x] Types
  - [x] Variables
  - [x] Literals
  - [x] Operators
  - [x] Enums
  - [x] Type casting
- [x] Printing
  - [x] `printf`
  - [x] Formatting
- [x] Array & Strings
- [x] Control Flow
  - [x] if
  - [x] else
  - [x] else if
  - [x] switch
- [x] Loops
  - [x] while
  - [x] do-while
  - [x] for
- [x] Functions
- [x] Pointers
- [x] Dynamic Memory
- [x] Structures
- [x] Macros & The Preprocessor
- [x] ~~The Standard Library~~

### LINKED ISSUE #5: M3 Content
- [x] Logging In
  - [x] SSH or PuTTY
- [x] Software and Tooling
- [x] Linux commands
- [x] Bash scripts
- [x] SLURM
- [x] Shared Filesystem
- [x] Challenges

### LINKED ISSUE #6: Parallel Computing Content
- [x] Parallel Programming
- [x] Parallel Techniques
- [x] Shared Memory Resources
- [x] Parallel Algorithms
- [x] OpenMP

### LINKED ISSUE #7: Distributed Computing Content
- [x] Distributed computing concepts
- [x] Compute clusters
- [x] Message Passing
- [x] OpenMPI

### PR DESCRIPTION
**Pull request by oraqlle**
## Brief

The first release of the HPC Training Book for Monash DeepNeuron.

## Chapters Added

- Getting Started
- Introduction to C
- M3
- Parallel Computing
- Distributed Computing

## Contributors and Reviewers

- @oraqlle 
- @Ozzywap 
- @UnciaBit 
- @jasparm 
- @mmib0001 
- @ankitaagosavi 

## Linked Issues

- Closes #1 
- Closes #2 
- Closes #4 
- Closes #3 
- Closes #5 
- Closes #6 
- Closes #7 
- Closes MonashDeepNeuron/HPC-Training-Challenges#2

## Related Repos

- [HPC Training Challenges](https://github.com/MonashDeepNeuron/HPC-Training-Challenges)

### CODE REVIEW

**Review by Ozzywap — APPROVED** [review]
Looks really good! I'm happy with this.

**Review by jasparm — APPROVED** [review]
Looks good

**Review by ankitaagosavi — APPROVED** [review]
looking really good!

**Review by UnciaBit — APPROVED** [review]
Looks good

**Review by mmib0001 — APPROVED** [review]
looks good to me great work!

**Pull request merged**
